// 정규 표현식 Regular Expression
// /apple/.test("apple")
// true
// /apple/.test("applq")
// false
// /a@a.com/.test("a@a.com")
// true
// /a@a.com/.test("b@a.com")
// false
// /\w@a.com/.test("2@a.com")
// true
// /\w@a.com/.test("2sdfwer1r44@a.com")
// true
// /^\w@a.com$/.test("2sdfwer1r44@a.com")
// false
// /^\w@a.com$/.test("4@a.com")
// true
// /^\w+@a.com$/.test("2sdfwer1r44@a.com")
// true
// /^\w?@a.com$/.test("2sdfwer1r44@a.com")
// false
// /^\w?@a.com$/.test("@a.com")
// true
// /^\w?@a.com$/.test("t@a.com")
// true
// /^\w?@a.com$/.test("trr@a.com")
// false
// /^\w*@a.com$/.test("@a.com")
// true
// /^\w*@a.com$/.test("s@a.com")
// true
// /^\w*@a.com$/.test("ss@a.com")
// true
// /^\w*@a.com$/.test("ssssssssssssssssssss@a.com")
// true
// /^\w+@\w+.\w+$/.test("asdfasdf@a.com")
// true
// /^\w+@\w+.\w+$/.test("asdfasdf@a;com")
// true
// /^\w+@\w+\.\w+$/.test("asdfasdf@a;com")
// false
// /^\w+@\w+\.\w+$/.test("asdfasdf@a.com")
// true
// /010-1234-5678/.test("010-1234-5678")
// true
// /^\d+-1234-5678$/.test("sdsf-1234-5678")
// false
// /^\d{3}-1234-5678$/.test("12345-1234-5678")
// false
// /^\d{3}-\d{3,4}-\d{4}$/.test("125-1234-5678")
// true
